In [1]:
import numpy as np

In [31]:
a = np.arange(19)
b = np.arange(19)
x,y = np.meshgrid(a,b)

In [32]:
x
x = np.reshape(x, (-1,1))
x.shape

(361, 1)

In [33]:
y
y = np.reshape(y, (-1,1))
y.shape

(361, 1)

In [34]:
x_y = np.concatenate((x, y), axis=1)
x_y.shape

(361, 2)

In [35]:
x_y = np.tile(x_y, (1, 3))
x_y.shape

(361, 6)

In [36]:
x_y = np.reshape(x_y, (-1, 2))
x_y.shape

(1083, 2)

In [37]:
x_y = np.expand_dims(x_y, 0)
x_y

array([[[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        ...,
        [18, 18],
        [18, 18],
        [18, 18]]])

In [38]:
x_y.shape

(1, 1083, 2)

In [39]:
help(np.tile)

Help on function tile in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetitions of `A`

In [90]:
a = np.random.randint(1,10,size=(3,5))
# a = np.expand_dims(a, -1)
a.shape

(3, 5)

In [91]:
from scipy.special import expit, softmax

class_scores = softmax(a)
class_scores

array([[7.74450939e-01, 1.04810537e-01, 5.21820938e-03, 2.59799347e-04,
        3.85576419e-02],
       [7.06207845e-04, 2.59799347e-04, 1.41845637e-02, 1.41845637e-02,
        7.06207845e-04],
       [5.21820938e-03, 7.06207845e-04, 1.91967195e-03, 3.85576419e-02,
        2.59799347e-04]])

In [92]:
class_scores = expit(a)
class_scores

array([[0.99987661, 0.99908895, 0.98201379, 0.73105858, 0.99752738],
       [0.88079708, 0.73105858, 0.99330715, 0.99330715, 0.88079708],
       [0.98201379, 0.88079708, 0.95257413, 0.99752738, 0.73105858]])

In [93]:
aa = np.max(class_scores, axis=-1)
aa

array([0.99987661, 0.99330715, 0.99752738])

In [97]:
box_classes = np.argmax(class_scores, axis=-1)
box_classes

array([0, 2, 3])

In [95]:
b = np.where(aa>=0.1)
b

(array([0, 1, 2]),)

In [98]:
box_classes[b]

array([0, 2, 3])

In [107]:
a = np.random.randint(1,10,size=(16,16*16*3,1))
a.shape

(16, 768, 1)

In [108]:
b = np.random.randint(1,10,size=(16,16*16*3,80))
b.shape

(16, 768, 80)

In [109]:
c = a*b
c.shape

(16, 768, 80)

In [111]:
d = np.argmax(c ,axis=-1)
d.shape

(16, 768)

In [146]:
e = np.max(c ,axis=-1)
e.shape

(16, 768)

In [135]:
f =  np.where(e>66)
len(f[0])

2704

In [158]:
g = b[f]
len(g)

2704

In [156]:
f[3][3]

IndexError: tuple index out of range

In [159]:
g.shape

(2704, 80)

In [157]:
h = d[f]
h.shape

(2704,)

In [165]:
i= e[f]
i.shape

(2704,)

In [168]:
j = c[f]
j.shape

(2704, 80)

In [153]:
inds = np.where(h==3)
inds

(array([   0,   14,   21,   52,   64,   71,   83,   86,   94,  117,  144,
         146,  154,  181,  201,  261,  276,  293,  299,  301,  313,  315,
         342,  345,  359,  371,  386,  392,  395,  403,  417,  436,  442,
         493,  503,  504,  517,  531,  539,  550,  571,  575,  584,  591,
         610,  613,  616,  617,  638,  663,  673,  674,  678,  683,  688,
         708,  742,  746,  749,  788,  789,  819,  826,  834,  842,  861,
         876,  921,  952,  956,  962,  965,  975,  977,  984,  985,  986,
        1004, 1017, 1018, 1022, 1027, 1040, 1044, 1050, 1052, 1053, 1060,
        1120, 1135, 1136, 1138, 1140, 1156, 1159, 1161, 1171, 1194, 1197,
        1205, 1240, 1248, 1307, 1324, 1337, 1341, 1347, 1349, 1362, 1363,
        1369, 1379, 1382, 1395, 1465, 1479, 1487, 1534, 1535, 1564, 1574,
        1576, 1590, 1602, 1603, 1605, 1609, 1612, 1618, 1619, 1623, 1656,
        1658, 1674, 1686, 1690, 1732, 1762, 1765, 1766, 1772, 1779, 1780,
        1794, 1800, 1813, 1819, 1827, 

In [169]:
clas = h[inds]
scores = i[inds]
scores.shape

(218,)